// import './globals.css'
// import { Inter } from 'next/font/google'
// import Navbar from './components/Navbar'
// import Footer from './components/Footer/Footer'
// import dynamic from 'next/dynamic'
// import { Metadata } from 'next'

// const Progress = dynamic(() => import('./components/progress/Progress'), {
//   loading: () => <p>Loading...</p>,
//   ssr: false
// })



// const inter = Inter({ subsets: ['latin'] })
// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//          <Navbar activeRoute="/" />
//         {children}
//          <Footer />
//         <Progress />
//         </body>
//     </html>
//   )
// }
import React from 'react';
import Head from 'next/head';
import './globals.css';
// import { Inter } from 'next/font/google';
import Navbar from './components/Navbar';
import Footer from './components/Footer/Footer';
import dynamic from 'next/dynamic';

// Dynamic import for Progress component
const Progress = dynamic(() => import('./components/progress/Progress'), {
  loading: () => <p>Loading...</p>,
  ssr: false,
});

// Inter font configuration
// const inter = new Inter({ subsets: ['latin'] });

// RootLayout component
const RootLayout: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        {/* You can add other meta tags, links, etc. here */}
      </Head>
      <body>
        <Navbar activeRoute="/" />
        {children}
        <Footer />
        <Progress />
      </body>
    </>
  );
};

export default RootLayout;

